
import { GoogleGenAI } from "@google/genai";

// Guidelines: The API key must be obtained exclusively from process.env.API_KEY.
// Guidelines: Use this process.env.API_KEY string directly when initializing the GoogleGenAI instance.

export const generateCharacterReference = async (prompt: string): Promise<string> => {
  try {
    // Guideline: Create client instance with process.env.API_KEY named parameter.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `Create a simple 2D cartoon character design sheet for animation based on this description: ${prompt}. 
            The style should be clean, flat vector art suitable for mobile animation apps like FlipaClip. 
            White background. Clear outlines.`
          }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        }
      }
    });

    // Guideline: Iterate through parts to find the inlineData (image).
    let imageUrl = '';
    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
        for (const part of parts) {
            if (part.inlineData) {
                // Construct data URL from base64 image bytes
                imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                break;
            }
        }
    }

    if (!imageUrl) {
      throw new Error("No image generated by the model.");
    }

    return imageUrl;
  } catch (error: any) {
    console.error("Gemini API Error details:", error);
    let errorMessage = "Failed to generate character.";
    
    if (error.message) {
        errorMessage = error.message;
    }
    
    throw new Error(errorMessage);
  }
};

export const generateAnimationIdea = async (): Promise<string> => {
   try {
    // Guideline: Obtain client instance directly within the call using process.env.API_KEY.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    // Guideline: Select 'gemini-3-flash-preview' for basic text tasks.
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: "Give me a short, fun, 2D animation exercise idea for a beginner. 1 sentence.",
    });
    // Guideline: Use .text property directly (not as a method).
    return response.text || "Animate a bouncing ball.";
  } catch (error) {
    console.error("Animation idea generation failed:", error);
    return "Animate a bouncing ball.";
  }
}
